export default {
  CreateClient: {
    name: 'New Client',
    cnpj: '80212855000115',
    corporate_name: 'Razao social',
    contact: '5594991008899',
  },
  UndefinedClient: {
    name: '',
    cnpj: '',
    corporate_name: '',
    contact: '',
  },
  UpdateClient: {
    name: 'New Client 2',
    cnpj: '80212855000115',
    corporate_name: 'Razao social update',
    contact: '5594991008899',
  },
  CreateAddress: {
    street: 'Rua Rex',
    number: '1234',
    complement: 'Casa',
    neighborhood: 'Bairro Local',
    city: 'Ourilândia',
    state: 'PA',
    zip_code: '68390000',
    latitude: '22222',
    longitude: '333333',
  },
  UpdateAddress: {
    street: 'Rua Sao Francisco',
    number: '2222',
    complement: 'Apartamento',
    neighborhood: 'Bairro Mineiro',
    city: 'Parauapebas',
    state: 'PA',
    zip_code: '68390000',
    latitude: '222222',
    longitude: '333333',
  },
  UndefinedAddress: {
    street: '',
    number: '',
    complement: '',
    neighborhood: '',
    city: '',
    state: '',
    zip_code: '',
    latitude: '',
    longitude: '',
  },
};
